@startuml
left to right direction
actor User as u
rectangle "Personal Task Management System" {
   usecase "Manage Tasks" as mt
     usecase "Create Task" as ctk
       usecase "Create Subtask" as cs
       cs ..> ctk : extends
     usecase "Update Task" as ut
       usecase "Complete Task" as cmpt
       usecase "Cancel Task" as cclt
       usecase "Change Title" as chgt
       usecase "Change Description" as chgd
       usecase "Change Priority" as chgp
       usecase "Change Due Date" as cdd
       usecase "Associate Tag" as asstg
       ut ..> cmpt : include
       ut ..> cclt : include
       ut ..> chgt : include
       ut ..> chgd : include
       ut ..> chgp : include
       ut ..> cdd : include
       ut ..> asstg : include
       ut ..> cdd : include
     usecase "Create Tag" as ctg
     mt ..> ctk : include
     mt ..> ut : include
     mt ..> ctg : include

   usecase "Manage Projects" as mp
     usecase "Create Project" as cp
     usecase "Assign Task to Project" as attp
     usecase "Remove Task from Project" as rtfp
     mp ..> cp : include
     mp ..> attp : include
     mp ..> rtfp : include

   usecase "Monitor Tasks" as mot
     usecase "Filter Tasks" as ft
     usecase "Sort Tasks" as st
     usecase "Search Task" as srch
     mot ..> ft : include
     mot ..> st : include
     mot ..> srch : include
}
u --> mt
u --> mp
u --> mot
@enduml
