@startuml
left to right direction
actor User as u
rectangle "Personal Task Management System" {
   usecase "Manage Tasks" as mt
     usecase "Create Task" as ctk
     usecase "Create Subtask" as cs
     usecase "Update Task" as ut
       usecase "Complete Task" as cmpt
       usecase "Cancel Task" as cclt
       usecase "Change Title" as chgt
       usecase "Change Description" as chgd
       usecase "Change Priority" as chgp
       usecase "Change Due Date" as cdd
       usecase "Associate Tag" as asstg
       ut ..> cmpt : include
       ut ..> cclt : include
       ut ..> chgt : include
       ut ..> chgd : include
       ut ..> chgp : include
       ut ..> cdd : include
       ut ..> asstg : include
       ut ..> cdd : include
     usecase "Create Tag" as ctg
     mt ..> ctk : include
     mt ..> cs : include
     mt ..> ut : include
     mt ..> ctg : include

   usecase "Manage Projects" as mp
     usecase "Create Project" as cp
     usecase "Assign Task to Project" as attp
     usecase "Remove Task from Project" as rtfp
     mp ..> cp : include
     mp ..> attp : include
     mp ..> rtfp : include

   usecase "View Tasks" as vt
     usecase "Filter Tasks" as ft
       usecase "Filter by Date Range" as fbdr
       ft ..> fbdr : include
     usecase "Sort Tasks" as st
       usecase "Sort by Due Date" as stbdd
       usecase "Sort by Priority" as stbp
       usecase "Sort by Status" as stbs
       usecase "Sort by Project" as stbpj
       usecase "Sort by Tag" as stbtg
       st ..> stbdd : include
       st ..> stbp : include
       st ..> stbs : include
       st ..> stbpj : include
       st ..> stbtg : include
     usecase "Search Task" as srch
       usecase "Search by Keyword" as shbk
       usecase "Seach by Date" as shbd
       srch ..> shbk : include
       srch ..> shbd : include
     vt ..> ft : include
     vt ..> st : include
     vt ..> srch : include
}
u --> mt
u --> mp
u --> vt
@enduml
